##  Saturated Steam table B.6

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('../figures/Module-4/Sat-steam-p-int1.xlsx', sheet_name='Sheet2', index_col=None, na_values=['NA'])
df.truncate(before  = 25, after = 38)

,Pressure (bar),Temperature (C),"Volume (l, m3/kg)","Volume (v, m3/kg)","Internal Energy (l, kJ/kg)","Internal Energy (v, kJ/kg)","Enthalpy (l, kJ/kg)","Enthalpy (v, kJ/kg)"
25,5.5,155.46,0.001097,0.34260,655.16,2563.9,655.76,2752.3
26,6.0,158.83,0.001101,0.31558,669.72,2566.8,670.38,2756.1
27,6.5,161.98,0.001104,0.29259,683.36,2569.4,684.08,2759.6
28,7.0,164.95,0.001108,0.27277,696.23,2571.8,697.00,2762.8
29,7.5,167.75,0.001111,0.25551,708.40,2574.0,709.24,2765.6
30,8.0,170.41,0.001115,0.24034,719.97,2576.0,720.86,2768.3
31,8.5,172.94,0.001118,0.22689,731.00,2577.9,731.95,2770.8
32,9.0,175.35,0.001121,0.21489,741.55,2579.6,742.56,2773.0
33,9.5,177.66,0.001124,0.20410,751.67,2581.2,752.74,2775.1
34,10.0,179.88,0.001127,0.19436,761.39,2582.7,762.52,2777.1
35,10.5,182.01,0.001130,0.18552,770.75,2584.1,771.94,2778.9
36,11.0,184.06,0.001133,0.17745,779.78,2585.5,781.03,2780.6
37,11.5,186.04,0.001136,0.17006,788.51,2586.7,789.82,2782.2
38,12.0,187.96,0.001138,0.16326,796.96,2587.8,798.33,2783.7

## Excerpt off steam table of B.7

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('../figures/Module-4/superheated-team-p10.xlsx', sheet_name='Sheet2', index_col=None, na_values=['NA'])
df

,Temperature (C),Pressure (bar),Volume (m3/kg),Internal Energy (kJ/kg),Enthalpy (kJ/kg),Entropy (J/g*K)
0,50.00,10,0.001012,209.18,210.19,0.70335
1,100.00,10,0.001043,418.80,419.84,1.30650
2,150.00,10,0.001090,631.41,632.50,1.84120
3,179.88,10,0.001127,761.39,762.52,2.13810
4,179.88,10,0.194360,2582.70,2777.10,6.58500
5,200.00,10,0.206020,2622.20,2828.30,6.69550
6,250.00,10,0.232750,2710.40,2943.10,6.92650
7,300.00,10,0.257990,2793.60,3051.60,7.12460
8,350.00,10,0.282500,2875.70,3158.20,7.30290

## Modified question of 7.35


Problem Statement
> A turbine discharges 200 kg/h of saturated steam at 10.0 bar absolute. It is desired to generate steam at 300 C and 10.0 bar by mixing the turbine discharge with a second stream of superheated steam of 350 C and 10.0 bar.

> 
- If 300 kg/h of the product steam is to be generated, how much heat must be added to the mixer?
- If instead the mixing is carried out adiabatically, at what rate is the product steam generated?

Preamble: This question is relatively basic and engages you on how to use the steam tables. Heat is covered in-depth in the next module but for now, you can consider the question as, How much more __enthalpy__ is needed to be added to the mixer.

1. Draw a diagram of the process taking place and write the relevant equation:
 
 
- ![](../figures/Module-4/question1.svg)


- $$\dot{m_1}H_1 + \dot{m_2}H_2 = \dot{m_3}H_3$$

- $$ H = Q  -W  \space or \space H_{total} = \sum {H} $$

2. List simplifications and assumptions
 - As mentioned above, treat heat as enthalpy.
 - If you have read into module 5; then assume work is negligable.

3. List known values 
 - Input Stream 1: 
  - $\dot{m_1} = 200\frac{kg}{hr} $
  - $H_1 = 762.5 \frac{kj}{kg}$
 - Input Stream 2: 
  - $\dot{m_2} = ? $
  - $H_2 = 3051.6 \frac{kj}{kg}$ From steam table B.6
 - Output Stream 3: 
  - $\dot{m_3} = ? $
  - $H_3 = 3158.2 \frac{kj}{kg}$ From steam table B.7
  
4. Solve the equations.
 In part i) we are given the total mass flow rate $\dot{m_3}$ So we can solve for $\dot{m_2}$ using conservation of mass. 
 $$ 300 = 200 + \dot {m_2} $$ 
 
 Using this value we plug into the __first half__ of the  energy balance
 
 $$200\frac{kg}{hr} \cdot  762.5 \frac{kj}{kg} + 100\frac{kg}{hr} \cdot  3051.6 \frac{kj}{kg} =  457660 \frac{kj}{hr}$$ 
 
 Since we want the exit stream at 350 C we need to check to see if the enthalpy we obtained corresponds with the desired enthalpy in the exit stream.
 
 $$ \dot{m_3}\cdot H_3 = 300\frac{kg}{hr} \cdot  3158.2 \frac{kj}{kg} =  947460 \frac{kj}{hr} $$
 
 It Doesn't correspond.  There is missing energy that needs to be added. This is simple addition: 
 
 $$ Energy\space Needed = 947460 \frac{kj}{hr} - 457660 \frac{kj}{hr} =  489800 \frac {kj}{hr}$$